### PR TITLE
Calendar links in the program.

### PR DESCRIPTION
**Pull request by kmccurley**
This seems to come close to working, though I found at least two bugs:
1. Android Google calendar will not import the ics file, even though it satisfies the [icalendar validator](https://icalendar.org/validator.html). This is perhaps not surprising, since Google calendar apparently does not accept many ical feeds. I found that [this app](https://play.google.com/store/apps/details?id=com.simplemobiletools.calendar) parsed the ics file on android.
2. I tried adding a URL as location in the ics file, but it gets ignored by google calendar.

The library code to produce the Google Calendar link is not part of this pull request, but it's pretty simple:
```
function googleCalendarLink($title, $startdate, $enddate, $details, $location=null) {
  $url = 'https://calendar.google.com/calendar/render?action=TEMPLATE&';
  $args = array('text' => $title,
                'dates' => "$startdate/$enddate",
                'details' => $details);
  if ($location) {
    $args['location'] = $location;
  }

  return $url . http_build_query($args);
}
```

### CODE REVIEW

**Comment by dstebila** [comment]
I suggest prefixing the event title with the conference name, e.g. "Crypto 2020: Opening Remarks" rather than just "Opening Remarks".

I don't think it's necessary to include the session chairs/moderators in the event description.  

Successfully tested on
- iPhone adding to Apple's iOS Calendar.app
- macOS, downloading ICS to file system then importing into Apple's macOS Calendar.app
- macOS, downloading ICS to file system then uploading into Microsoft Office 365 Outlook web calendar

I have Outlook on my iPhone, but I don't think there's a way to import this into Outlook via the iPhone, as there's currently no way in iOS to change your default calendar program, so ICS files can only trigger Apple's Calendar.app, not Outlook.

**Comment by dstebila** [comment]
If you decide to add a [web Outlook link](https://github.com/spatie/calendar-links/blob/master/src/Generators/WebOutlook.php) similar to the Google Calendar link, I can test it.

**Comment by kmccurley** [comment]
I included the conference name in the title - that's a great suggestion. I also moved the link to the program to the top of the description, because that is most important.

As for the moderator fielld, it sometimes gets used as a subtitle, so I think we should leave it. I expanded it to include the titles and authors of papers, which makes a very large description but it's now ordered better. 
image

Note that we need to change the link back to the program to replace 2020-test by 2020 when we finally submit it.

**Comment by dstebila** [comment]
I just imported 19 events into my calendar from the program, worked perfectly!  Thanks!

**Pull request merged**
